name: Build and push Navigator front to AWS ECR

on:
  workflow_dispatch:

concurrency:
  group: navigator-front-${{ github.ref }}-ci-1
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      APPLICATION: 'frontend'
      PROJECT: navigator
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ENVIRONMENT: 'prod'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.18.0

      - name: Install dependencies
        run: |
          cd front
          yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ var.AWS_ACCOUNT_ID }}:role/github_access
          aws-region: ${{ var.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: .
        env:
          ECR_REGISTRY: ${{ var.AWS_ACCOUNT_ID }}.dkr.ecr.${{ var.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ${{ var.PROJECT }}-${{ var.APPLICATION }}
          IMAGE_TAG: ${{ var.github-sha }}
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg COMMIT_HASH=${{ var.github-sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        shell: bash